export const FLIP_CARD = 'FLIP_CARD';
export const SET_CURRENT_PLAYER = 'SET_CURRENT_PLAYER';
export const SET_LAST_CARD_FLIPPED = 'SET_LAST_CARD_FLIPPED';
export const ADD_POINT = 'ADD_POINT';
export const SET_PLAYER_NAME = 'SET_PLAYER_NAME';
export const TOGGLE_SOUND = 'TOGGLE_SOUND';
